syntax = "proto3";

package app.v1;

enum Environment {
    ENVIRONMENT_UNSPECIFIED = 0;
    ENVIRONMENT_DEV = 1;
    ENVIRONMENT_PROD = 2;
}
message Settings {
    Environment env = 1;

    string domain = 2;
    string admin_email = 3;

    ApiServiceSettings api_service_settings = 20;
    StorageServiceSettings storage_service_settings = 21;
}

message ApiServiceSettings {
    string hostname = 1;
    int32 port = 2;
    JwtSettings jwt_settings = 3;
}

message JwtSettings {
    string secret = 1;
    string algorithm = 2;
    int32 access_token_expiration_seconds = 3;
    int32 refresh_token_expiration_seconds = 4;
}

message StorageServiceSettings {
    string hostname = 1;
    int32 port = 2;
}