syntax = "proto3";

package app.v1;

import "account.proto";
import "user_data.proto";

enum SubjectType {
    SUBJECT_TYPE_UNSPECIFIED = 0;
    SUBJECT_TYPE_ACCOUNT = 1;
    SUBJECT_TYPE_USER_DATA = 2;
}

service StorageService {
  rpc Insert(InsertRequest) returns (InsertResponse) {};
  rpc Get(GetRequest) returns (GetResponse) {};
  rpc List(ListRequest) returns (ListResponse) {};
  rpc Update(UpdateRequest) returns (UpdateResponse) {};
  rpc Delete(DeleteRequest) returns (DeleteResponse) {};
  rpc DeleteAll(DeleteAllRequest) returns (DeleteAllResponse) {};
}

message InsertRequest {
  oneof subject {
    Account account = 1;
    UserData user_data = 2;
  }
}

message InsertResponse {
  string id = 1;
}

message GetRequest {
  SubjectType subject_type = 1;
  string id = 2;
  string user_id = 3;
}

message GetResponse {
  oneof subject {
    Account account = 1;
    UserData user_data = 2;
  }
}

message AccountFilter {
  string email = 1;
}

message ListRequest {
  SubjectType subject_type = 1;
  string user_id = 2;
  oneof filter {
    AccountFilter account_filter = 100;
  }
}

message ListResponse {
  repeated Account accounts = 1;
  repeated UserData user_data = 2;
}

message UpdateRequest {
  oneof subject {
    Account account = 1;
    UserData user_data = 2;
  }
}

message UpdateResponse {
}

message DeleteRequest {
  SubjectType subject_type = 1;
  string id = 2;
  string user_id = 3;
}

message DeleteResponse {
  int32 deleted_count = 1;
}

message DeleteAllRequest {
  SubjectType subject_type = 1;
  string user_id = 2;
}

message DeleteAllResponse {
    int32 deleted_count = 1;
}