FROM nginx:stable-alpine

WORKDIR /usr/local/app

ENV SETTINGS_FILE=./runtime/settings.yaml

COPY ./runtime/nginx/nginx-prod.conf /etc/nginx/nginx.conf
COPY ./runtime/web /var/www/html

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]