events {}

http {
    access_log /dev/stdout;
    
    include       mime.types;
    default_type  application/octet-stream;
    
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    server {
        listen 443 ssl; # managed by Certbot
        server_name localhost;

        ssl_certificate localhost+2.pem;
        ssl_certificate_key localhost+2-key.pem;

        location /api/ {
            proxy_pass http://[API_HOSTNAME]:[API_PORT]/;
            proxy_http_version 1.1;             # required for streaming
            proxy_buffering off;                # recommended for streaming
            proxy_request_buffering off;        # recommended for streaming 
            proxy_pass_trailers on;             # required for gRPC
        }

        location / {
            root /var/www/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }

    server {
        listen 80;
        server_name localhost;

        if ($host = localhost) {
            return 301 https://$host$request_uri;
        } # managed by Certbot

        return 404; # managed by Certbot
    }
}
